[build]
  publish = "."

[[redirects]]
  from = "/book"
  to = "/customer.html"
  status = 200

[[redirects]]
  from = "/partner"
  to = "/partner.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/ops"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/track"
  to = "/track.html"
  status = 200
